
name: GH Pages Build

on:
  push:
    branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write      
        steps:
        - uses: actions/checkout@v2
        - name: Build and Deploy to GH Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
